import {test} from 'node:test';
import assert from 'node:assert/strict';
import {validateProposal,TASK,outputJSONSchema,DEFAULT_MODEL} from '../lib/ai/contracts.mjs';
import {callExtraction,readLimitedJSON} from '../lib/ai/service.mjs';
import {applyProposal,buildScope} from '../lib/ai/client.mjs';
import {makeRecord,readWorkbook,extract} from '../lib/workbook.mjs';
import {readFileSync} from './helpers/fixtures.mjs';
const digest='a'.repeat(64);
const cells=[{sheet:'PPE',cell:'A1',raw:'Manufacturer Part Number',formula:null,eligibleAnchor:false},{sheet:'PPE',cell:'A2',raw:'000123',formula:null,eligibleAnchor:true},{sheet:'PPE',cell:'B2',raw:'Glove SZ 2L; 100/BX',formula:null,eligibleAnchor:true},{sheet:'PPE',cell:'C1',raw:'Annual Volume',formula:null,eligibleAnchor:false},{sheet:'PPE',cell:'C2',raw:'0',formula:null,eligibleAnchor:true},{sheet:'PPE',cell:'D2',raw:'CA',formula:null,eligibleAnchor:true}];
const input={mode:'enrich',digest,scopeId:'scope',cells,records:[{id:'r1',sheet:'PPE',anchors:['B2'],currentValues:{E:'Glove SZ 2L; 100/BX'}}]};
const cite=(cell,quote)=>({sheet:'PPE',cell,quote});
const field=(column,value,evidence,other={})=>({column,value,reason:'Review literal source evidence.',kind:'source_span',identifierType:'not_identifier',evidence,...other});
const result=()=>({items:[{recordId:'r1',sheet:'PPE',anchors:['B2'],section:'',boundaryReason:'One explicit product occurrence.',ambiguous:false,fields:[field('G','2L',[cite('B2','2L')]),field('I','000123',[cite('A2','000123'),cite('A1','Manufacturer Part Number')],{identifierType:'manufacturer'}),field('K','0',[cite('C2','0'),cite('C1','Annual Volume')])],extras:[]}],warnings:[]});
test('AI diagnostics report actual validation without credentials and cannot affect candidates',async()=>{
 const mock=async()=>Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(result())}]}]}),events=[];
 const baseline=await callExtraction(input,{key:'secret-debug-key',fetchImpl:mock});
 assert.deepEqual(await callExtraction(input,{key:'secret-debug-key',fetchImpl:mock,observer:e=>events.push(e)}),baseline);
 assert.deepEqual(await callExtraction(input,{key:'secret-debug-key',fetchImpl:mock,observer:()=>{throw Error('debug failed');}}),baseline);
 assert.ok(events.some(e=>e.status==='validated'));assert.ok(!JSON.stringify(events).includes('secret-debug-key'));
 const failed=[];await assert.rejects(callExtraction(input,{key:'secret-debug-key',fetchImpl:async()=>Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'{}'}]}]}),observer:e=>failed.push(e)}));assert.ok(!failed.some(e=>e.status==='validated'));
});
test('valid raw size, leading-zero manufacturer part and explicit annual zero are retained',()=>assert.equal(validateProposal(input,result()).items[0].fields[1].value,'000123'));
test('fabricated quotes, phantom cells, approval fields and dropped records are rejected',()=>{for(const mutate of [r=>r.items[0].fields[0].evidence[0].quote='2XL',r=>r.items[0].fields[0].evidence[0].cell='Z99',r=>r.items[0].approved=true,r=>r.items=[]]){const r=result();mutate(r);assert.throws(()=>validateProposal(input,r));}});
test('namespace and annual-period proof are mandatory',()=>{const r=result();r.items[0].fields[1].evidence=[cite('A2','000123')];assert.throws(()=>validateProposal(input,r),/namespace/);r.items[0].fields=r.items[0].fields.filter(f=>f.column==='K');r.items[0].fields[0].evidence=[cite('C2','0')];assert.throws(()=>validateProposal(input,r),/annual-period/);});
test('unfamiliar CA cannot be silently aliased to CS; bare units cannot supply pack defaults',()=>{const r=result();r.items[0].fields=[field('L','CS',[cite('D2','CA')],{kind:'normalization'})];assert.throws(()=>validateProposal(input,r),/UOM/);r.items[0].fields=[field('M','1',[cite('D2','CA')],{kind:'interpretation'})];assert.throws(()=>validateProposal(input,r),/Pack/);});
test('enrichment cannot move or duplicate item boundaries; discovery excludes header anchors',()=>{const r=result();r.items[0].anchors=['A1'];assert.throws(()=>validateProposal(input,r));const d={...input,mode:'discover',records:[]};r.items[0].recordId='';assert.throws(()=>validateProposal(d,r),/anchor/);});
test('AI merge preserves accepted values and never creates approvals',()=>{const book={sheets:[{name:'PPE',cells:Object.fromEntries(cells.map(c=>[c.cell,c]))}]},r=makeRecord(book.sheets[0],['B2']);r.id='r1';r.values.G={value:'human size',evidence:['B2'],reason:'Human edit',status:'edited',direct:false};const applied=applyProposal([r],book,input,{proposal:result(),digest,scopeId:'scope'});assert.equal(applied.records[0].values.G.value,'human size');assert.equal(applied.records[0].values.I.status,'pending');assert.equal(applied.records[0].boundary,'pending');assert.throws(()=>applyProposal([r],book,input,{proposal:result(),digest:'b'.repeat(64),scopeId:'scope'}));});
test('Responses request is fixed, tool-free, store:false; raw key/error never returns',async()=>{let sent;const mock=async(url,init)=>{sent=JSON.parse(init.body);assert.equal(init.headers.Authorization,'Bearer private-test-key');return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(result())}]}]});};const value=await callExtraction(input,{key:'private-test-key',fetchImpl:mock});assert.equal(sent.store,false);assert.equal(sent.model,DEFAULT_MODEL);assert.equal(sent.instructions,TASK);assert.equal(sent.tools,undefined);assert.deepEqual(sent.text.format.schema,outputJSONSchema);assert.ok(!JSON.stringify(value).includes('private-test-key'));});
test('missing key, incomplete/refused response and bad evidence fail closed',async()=>{await assert.rejects(callExtraction(input,{}),/not configured/);for(const output of [{status:'incomplete',output:[]},{status:'completed',output:[{type:'message',content:[{type:'refusal',refusal:'No'}]}]},{status:'completed',output:[{type:'message',content:[{type:'output_text',text:'{}'}]}]}])await assert.rejects(callExtraction(input,{key:'test',fetchImpl:async()=>Response.json(output)}));});
test('retry only transient provider failures and sanitize credential errors',async()=>{let calls=0;await callExtraction(input,{key:'test',fetchImpl:async()=>++calls===1?new Response('',{status:500}):Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(result())}]}]})});assert.equal(calls,2);await assert.rejects(callExtraction(input,{key:'private-test-key',fetchImpl:async()=>new Response('private-test-key',{status:401})}),e=>!e.message.includes('private-test-key'));});
test('request body size and original-source scope bounds are enforced',async()=>{await assert.rejects(readLimitedJSON(new Request('https://example.invalid',{method:'POST',body:'abcdef'}),3),/large/);const book={sheets:[{name:'PPE',cells:Object.fromEntries(cells.map(c=>[c.cell,c]))}]};assert.throws(()=>buildScope(book,[],{mode:'discover',digest,scopeId:'s',sheet:'PPE',start:1,end:400}));});
test('all five actual layouts fit bounded per-ten-item scopes with immutable source evidence',()=>{const paths=['../attachments/8e933fef-5f19-4144-b944-9b1961b4ee51/Safety PPE Supplies 2024 FL.xlsx','../attachments/a8b4fa56-bbb4-4d76-8e6a-50a859f829fc/RFQ for PPE.xlsx','../attachments/e6f63120-98ee-4723-92b3-e6959045d7c5/TESLA PPE RFP April 2025.xlsx','../attachments/fac704a8-4ebc-4e40-9bab-2a32a330cd7a/grainger-030926.xlsx','../attachments/5c3b8658-ae6e-4236-aa3e-731f507b82fc/PPE List.xlsx'];for(const path of paths){const book=readWorkbook(new Uint8Array(readFileSync(path))),records=extract(book).records;for(let i=0;i<records.length;i+=10){const scope=buildScope(book,records.slice(i,i+10),{digest,scopeId:'sample-'+i});assert.ok(scope.cells.length<=900);for(const c of scope.cells)assert.equal(c.raw,book.sheets.find(s=>s.name===c.sheet).cells[c.cell].raw);}}});
test('identifier tokens cannot lose leading zeros through clipped evidence',()=>{const r=result();r.items[0].fields=[field('I','123',[cite('A2','123'),cite('A1','Manufacturer Part Number')],{identifierType:'manufacturer'})];assert.throws(()=>validateProposal(input,r),/altered/);r.items[0].fields=[];r.items[0].extras=[{name:'Source Product ID',value:'123',meaning:'Original ID',benefit:'Matching identity',reason:'Review ID',evidence:[cite('A2','123')]}];assert.throws(()=>validateProposal(input,r),/altered/);});
test('competing AI values disable blanket direct approval and retain the original',()=>{const book={sheets:[{name:'PPE',cells:Object.fromEntries(cells.map(c=>[c.cell,c]))}]},r=makeRecord(book.sheets[0],['B2']);r.id='r1';r.values.E={value:'Glove SZ 2L; 100/BX',evidence:['B2'],reason:'Source',status:'pending',direct:true};const p=result();p.items[0].fields=[field('E','Glove',[cite('B2','Glove')])];const out=applyProposal([r],book,input,{proposal:p,digest,scopeId:'scope'});assert.equal(out.records[0].values.E.value,r.values.E.value);assert.equal(out.records[0].values.E.direct,false);assert.equal(out.records[0].values.E.alternatives[0].status,'pending');});
test('AI agreement never hides prior packaging-conflict evidence',()=>{const book={sheets:[{name:'PPE',cells:Object.fromEntries(cells.map(c=>[c.cell,c]))}]},r=makeRecord(book.sheets[0],['B2']);r.id='r1';r.values.M={value:'100',evidence:['B2','D2'],reason:'Conflicting packaging levels need review.',status:'pending',direct:false};const p=result();p.items[0].fields=[field('M','100',[cite('B2','100/BX')])];const applied=applyProposal([r],book,input,{proposal:p,digest,scopeId:'scope'});assert.match(applied.records[0].values.M.reason,/Conflicting/);assert.ok(applied.records[0].values.M.evidence.includes('D2'));assert.equal(applied.records[0].values.M.status,'pending');});

test('Gemini uses a fixed Google endpoint and header credential with the same grounded output contract',async()=>{
 let body;const out=await callExtraction(input,{provider:'gemini',key:'gemini-test-secret',fetchImpl:async(url,init)=>{assert.match(url,/^https:\/\/generativelanguage\.googleapis\.com\/v1beta\/models\/gemini-3\.8-flash:generateContent$/);assert.ok(!url.includes('gemini-test-secret'));assert.equal(init.headers['x-goog-api-key'],'gemini-test-secret');assert.equal(init.headers.Authorization,undefined);body=JSON.parse(init.body);return Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(result())}]}}]});}});
 assert.equal(body.systemInstruction.parts[0].text,TASK);assert.deepEqual(body.generationConfig.responseJsonSchema,outputJSONSchema);assert.equal(body.tools,undefined);assert.equal(body.cachedContent,undefined);assert.equal(out.provider,'gemini');assert.equal(out.proposal.items[0].fields[1].value,'000123');assert.ok(!JSON.stringify(out).includes('gemini-test-secret'));
});
test('Gemini refusals, truncation, malformed evidence and unexpected tool content fail closed',async()=>{
 for(const response of [{promptFeedback:{blockReason:'SAFETY'}},{candidates:[{finishReason:'MAX_TOKENS',content:{parts:[{text:'{}'}]}}]},{candidates:[{finishReason:'STOP',content:{parts:[{text:'{}'}]}}]},{candidates:[{finishReason:'STOP',content:{parts:[{functionCall:{name:'approve'}}]}}]}])await assert.rejects(callExtraction(input,{provider:'gemini',key:'test',fetchImpl:async()=>Response.json(response)}));
});
test('Gemini credential failures stay sanitized; invalid provider/model configuration never sends data',async()=>{
 await assert.rejects(callExtraction(input,{provider:'gemini',key:'private-test-key',fetchImpl:async()=>new Response('private-test-key',{status:403})}),e=>!e.message.includes('private-test-key'));
 for(const config of [{provider:'untrusted'},{provider:'gemini',model:'gemini-model?key=secret'}])await assert.rejects(callExtraction(input,{...config,key:'test',fetchImpl:async()=>{throw Error('Should not call provider');}}),/configuration/);
});

test('Google invalid-key response is classified without returning raw provider content',async()=>{await assert.rejects(callExtraction(input,{provider:'gemini',key:'private-test-key',fetchImpl:async()=>Response.json({error:{message:'API key not valid. Please pass a valid API key.',details:[{reason:'API_KEY_INVALID',secret:'private-test-key'}]}},{status:400})}),e=>e.status===503&&e.message.includes('Gemini API key is invalid')&&!e.message.includes('private-test-key'));});
