import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from './helpers/fixtures.mjs';
import {createHash} from 'node:crypto';
import {makeRecord,readWorkbook,extract} from '../lib/workbook.mjs';
import {createReviewController,buildCanonical,checkCanonical} from '../lib/canonical/bridge.mjs';
import {coverageIndex,prepareCoverage,applyCoverage,approveLayout} from '../lib/canonical/coverage.mjs';
import {exportReviewedWorkbook,finalReadiness} from '../lib/canonical/export.mjs';
import {buildScope,applyProposal} from '../lib/ai/client.mjs';
const digest='a'.repeat(64),hash=b=>createHash('sha256').update(b).digest('hex');
function setup(){const book={sheets:[{name:'Bid',hidden:'visible',hiddenRows:[],cells:{A1:{raw:'Description',type:'inlineStr',formula:null},A2:{raw:'Glove',type:'inlineStr',formula:null}}}]},r=makeRecord(book.sheets[0],['A2']),controller=createReviewController();r.values.E={value:'Glove',evidence:['A2'],reason:'Direct labeled source',direct:true,status:'pending'};return {book,records:[r],controller,columns:{},name:'bid.xlsx',digest,templateDigest:digest};}
function confirm(s){const r=s.records[0],before=structuredClone(r);r.boundary='include';s.controller.record(before,r,'Reviewer confirms one source item.');s.controller.automate(s.records,s.book);const index=coverageIndex(s.book,s.records,s.controller);for(const sheet of s.book.sheets){const selected=new Set(s.records.filter(r=>r.sheet===sheet.name).flatMap(r=>[...r.anchors,...Object.values(r.values).flatMap(f=>f.evidence),...Object.values(r.extras).flatMap(f=>f.evidence)]));for(const disposition of ['item','excluded']){const addresses=Object.keys(sheet.cells).filter(a=>selected.has(a)===(disposition==='item'));for(let i=0;i<addresses.length;i+=100)applyCoverage(s.controller,index,prepareCoverage(index,{sheet:sheet.name,addresses:addresses.slice(i,i+100),disposition,role:disposition==='item'?'customer_specification':'context',reason:'Test-only source subset: reviewer confirms selected evidence and explicitly excludes other cells.'}));}approveLayout(s.controller,index,sheet.name,'Test-only source subset, explicit source coverage.');}}
test('automatic blanks and literal text copies pass final canonical validation without field review events',()=>{const s=setup();s.controller.automate(s.records,s.book);const r=s.records[0];assert.equal(r.values.E.status,'auto_accepted');assert.equal(r.values.K.status,'auto_blank');assert.equal(s.controller.fields.size,0);confirm(s);const snap=buildCanonical(s);assert.deepEqual(checkCanonical(snap,{reviewed:true,coverage:true,final:true}),[]);assert.equal(snap.run.items[0].fields.annual_usage.presence,'absent');assert.equal(snap.run.items[0].fields.description_primary.review_event_id,null);});
test('forged status, altered values, formulas, conflicts and meaningful numeric/identifier fields do not auto approve',()=>{const s=setup(),r=s.records[0];r.values.E.status='auto_accepted';assert.equal(buildCanonical(s).run.items[0].fields.description_primary.resolution,'unresolved');r.values.E.status='pending';r.values.E.value='Invented';s.controller.automate(s.records,s.book);assert.equal(r.values.E.status,'pending');r.values.E.value='Glove';s.book.sheets[0].cells.A2.formula='A1';s.controller.automate(s.records,s.book);assert.equal(r.values.E.status,'pending');s.book.sheets[0].cells.A2.formula=null;r.values.E.alternatives=[{value:'Other',evidence:['A2'],reason:'Conflict'}];s.controller.automate(s.records,s.book);assert.equal(r.values.E.status,'pending');for(const k of ['I','K','L','M'])r.values[k]={value:'Glove',evidence:['A2'],reason:'Unverified meaning',direct:true,status:'pending'};s.controller.automate(s.records,s.book);for(const k of ['I','K','L','M'])assert.equal(r.values[k].status,'pending');r.values.B.alternatives=[{value:'1'}];r.values.C.evidence=['A2'];s.controller.automate(s.records,s.book);assert.equal(r.values.B.status,'pending');assert.equal(r.values.C.status,'pending');});
test('new semantic facts replace automatic blanks, and cleaned narrative defaults are not artificial conflicts',()=>{const s=setup(),r=s.records[0];r.values.E.direct=false;s.controller.automate(s.records,s.book);const input=buildScope(s.book,s.records,{digest,scopeId:'test-scope'}),proposal={items:[{recordId:r.id,sheet:r.sheet,anchors:r.anchors,section:'',ambiguous:false,boundaryReason:'One item',fields:[{column:'E',value:'Protective glove',evidence:[{sheet:'Bid',cell:'A2',quote:'Glove'}],reason:'Product wording',kind:'normalization',identifierType:'not_identifier'},{column:'F',value:'Glove',evidence:[{sheet:'Bid',cell:'A2',quote:'Glove'}],reason:'Additional wording',kind:'source_span',identifierType:'not_identifier'}],extras:[]}],warnings:[]};const applied=applyProposal(s.records,s.book,input,{digest,scopeId:'test-scope',proposal});assert.equal(applied.records[0].values.E.value,'Protective glove');assert.equal(applied.records[0].values.E.alternatives,undefined);assert.equal(applied.records[0].values.F.status,'pending');s.controller.reconcile(s.records,applied.records);s.controller.automate(applied.records,s.book);assert.equal(applied.records[0].values.F.status,'pending');});
test('Daikin actual source subset exports automatic unsupported blanks and copied description with readback',async()=>{const proposalBytes=readFileSync('../attachments/8e933fef-5f19-4144-b944-9b1961b4ee51/Safety PPE Supplies 2024 FL.xlsx'),templateBytes=readFileSync('public/template.xlsx'),book=readWorkbook(proposalBytes),records=[extract(book).records[0]],controller=createReviewController(),s={book,records,controller,columns:{},name:'Daikin.xlsx',digest:hash(proposalBytes),templateDigest:hash(templateBytes),proposalBytes,templateBytes,expectedSourceDigest:hash(proposalBytes),coverageConfirmed:true};controller.automate(records,book);confirm(s);const r=records[0],before=structuredClone(r);for(const f of Object.values(r.values))if(f.status==='pending')f.status=f.value?'accepted':'blank';controller.record(before,r,'Test reviewer confirms remaining meaningful fields.');const old=structuredClone(r);for(const [name,f]of Object.entries(r.extras)){s.columns[name]='approved';f.status='accepted';controller.column(name,'approved');}controller.record(old,r,'Test reviewer retains supplied stock codes in approved source columns.');confirm(s);assert.deepEqual(finalReadiness(s).messages,[]);const out=readWorkbook(await exportReviewedWorkbook(s)).sheets.find(s=>s.name==='AI BID IDENTIFICATION TEMPLATE');assert.equal(out.cells.E2.raw,book.sheets[0].cells.D7.raw);assert.equal(out.cells.K2,undefined);assert.equal(out.cells.M2,undefined);assert.equal(r.values.K.status,'auto_blank');});
