import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from './helpers/fixtures.mjs';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {validate} from '../lib/canonical/validator.mjs';
import {buildCanonical,checkCanonical,createReviewController} from '../lib/canonical/bridge.mjs';
import {readWorkbook,extract,makeRecord} from '../lib/workbook.mjs';
const fixture=()=>JSON.parse(readFileSync('lib/canonical/reference/example.valid.json','utf8'));
const codes=e=>[...new Set(e.map(e=>e.code))].sort();
test('JavaScript port matches authoritative Python for shape, review and source failures',()=>{
 const mutations=[()=>{},r=>r.schema_version='1.0.0',r=>r.extra=true,r=>delete r.items[0].fields.size,r=>r.revision=-1,r=>r.evidence.push(structuredClone(r.evidence[0])),r=>r.evidence[0].sheet_id='missing',r=>r.evidence[0].span={start:0,end:1,quoted_text:'wrong'},r=>r.items[0].lineage.source_ranges=['Z999'],r=>r.regions[0].file_id='missing',r=>r.items[0].fields.description_primary.candidates[0].value='Invented',r=>r.items[0].fields.description_primary.candidates[0].evidence_ids=[],r=>r.items[0].fields.description_primary.candidates[0].input_candidate_ids=['missing'],r=>r.items[0].fields.description_primary.candidates[0].method='derived',r=>r.items[0].fields.description_primary.candidates[0].input_candidate_ids=['c1'],r=>r.items[0].fields.description_primary.selected_candidate_id='missing',r=>r.items[0].fields.description_primary.resolution='reviewer_accepted',r=>r.items[0].fields.description_primary.confidence_assessment.calibrated_probability=0.5,r=>r.evidence[0].formula='SUM(A1)',r=>r.evidence[0].semantic_role='quoted_alternate',r=>r.source_files[0].source_role='historical_response',r=>r.items[0].inclusion='excluded',r=>r.regions[0].coverage=[],r=>r.regions[0].resolution='unresolved',r=>r.items[0].fields.description_primary.decision_revision=1];
 for(const mutate of mutations)for(const final of [false,true]){const r=fixture();mutate(r);const py=spawnSync(process.env.PYTHON || 'python3',['-c',"import sys,json;sys.path.insert(0,'lib/canonical/reference');from validator import validate;r=json.load(sys.stdin);print(json.dumps(validate(r,final="+(final?'True':'False')+")))"],{input:JSON.stringify(r),encoding:'utf8'});assert.equal(py.status,0,py.stderr);assert.deepEqual(codes(validate(r,{final})),codes(JSON.parse(py.stdout)));}
});
const digest='b'.repeat(64),templateDigest='a'.repeat(64);
function setup(){const book={sheets:[{name:'PPE',cells:{A1:{raw:'Manufacturer Part Number',type:'inlineStr',formula:null},A2:{raw:'000123',type:'inlineStr',formula:null},B2:{raw:'Glove',type:'inlineStr',formula:null},C1:{raw:'Annual Volume',type:'inlineStr',formula:null},C2:{raw:'0',type:'n',formula:null},D2:{raw:'BT',type:'inlineStr',formula:null}}}]},r=makeRecord(book.sheets[0],['B2']),controller=createReviewController();r.values.E={value:'Glove',evidence:['B2'],reason:'Source description',status:'pending',direct:true};r.values.I={value:'000123',evidence:['A2'],reason:'Manufacturer part from header A1',status:'pending'};r.values.K={value:'0',evidence:['C2'],reason:'Annual volume from C1',status:'pending'};r.values.L={value:'BT',evidence:['D2'],reason:'Source bottle unit preserved',status:'pending'};return{book,r,controller};}
function review(r,controller){const before=structuredClone(r);r.boundary='include';for(const f of Object.values(r.values)){f.status=f.value?'accepted':'blank';}controller.record(before,r,'Explicit scoped reviewer decision.');}
const snapshot=(s)=>buildCanonical({book:s.book,records:[s.r],columns:{},name:'test.xlsx',digest,templateDigest,controller:s.controller});
test('reviewed fields bridge to all twelve typed slots; zero, unknown units and leading zeros survive',()=>{const s=setup();review(s.r,s.controller);const snap=snapshot(s);assert.deepEqual(checkCanonical(snap),[]);const f=snap.run.items[0].fields;assert.equal(Object.keys(f).length,12);assert.equal(f.manufacturer_part_primary.candidates[0].value.text,'000123');assert.equal(f.annual_usage.candidates[0].value.amount.value,'0');assert.equal(f.customer_uom.candidates[0].value.code,'OTHER');assert.equal(f.customer_uom.candidates[0].value.label,'BT');assert.equal(f.size.resolution,'accepted_unknown');assert.ok(validate(snap.run,{final:true,trusted:snap.trusted}).some(e=>e.code==='LAYOUT_UNRESOLVED'));});
test('UI status and model-shaped approval flags cannot mint controller approval; edits invalidate signatures',()=>{const s=setup();s.r.values.E.status='accepted';assert.equal(snapshot(s).run.items[0].fields.description_primary.resolution,'unresolved');assert.ok(checkCanonical(snapshot(s),{reviewed:true}).some(e=>e.code==='REVIEW_UNVERIFIED'));s.r.values.E.status='pending';review(s.r,s.controller);assert.deepEqual(checkCanonical(snapshot(s),{reviewed:true}),[]);s.r.values.E.value='Changed outside review';assert.equal(snapshot(s).run.items[0].fields.description_primary.resolution,'unresolved');s.r.anchors=['A2'];assert.equal(snapshot(s).run.items[0].inclusion,'candidate');});
test('source tampering, unverified formulas, invalid numbers and unknown annual periods block contract checks',()=>{const s=setup();review(s.r,s.controller);const snap=snapshot(s);snap.run.evidence[0].raw_value='Fabricated';assert.ok(checkCanonical(snap).some(e=>e.code==='SOURCE_VALUE_MISMATCH'));s.book.sheets[0].cells.B2.formula='SUM(A1)';assert.ok(checkCanonical(snapshot(s)).some(e=>e.code==='FORMULA_UNVERIFIED'));s.book.sheets[0].cells.B2.formula=null;s.book.sheets[0].cells.C1.raw='Monthly volume';assert.ok(checkCanonical(snapshot(s)).some(e=>e.code==='ANNUAL_BASIS'));const before=structuredClone(s.r);s.r.values.K.value='10-20';s.r.values.K.status='edited';s.controller.record(before,s.r,'Reviewer edit');assert.ok(checkCanonical(snapshot(s)).some(e=>e.code==='CANONICAL_VALUE_INVALID'));});
test('column approval remains distinct from exact extension value approvals',()=>{const s=setup();s.r.extras['Source ID']={value:'000123',evidence:['A2'],reason:'Preserves source identifier.',status:'pending'};s.controller.column('Source ID','approved');const x=buildCanonical({book:s.book,records:[s.r],columns:{'Source ID':'approved'},name:'test.xlsx',digest,templateDigest,controller:s.controller});assert.deepEqual(checkCanonical(x),[]);assert.equal(x.run.extensions[0].output_position,14);assert.equal(x.trusted.extension_value_approvals.size,0);assert.ok(validate(x.run,{final:true,trusted:x.trusted}).some(e=>e.code==='COLUMN_VALUE_UNVERIFIED'));});
test('unit and manufacturer edits invalidate dependent canonical decisions',()=>{const s=setup();review(s.r,s.controller);const before=structuredClone(s.r);s.r.values.L.value='EA';s.r.values.L.status='edited';s.r.values.H.value='New manufacturer';s.r.values.H.status='edited';s.controller.record(before,s.r,'Reviewer correction');const f=snapshot(s).run.items[0].fields;assert.equal(f.annual_usage.resolution,'unresolved');assert.equal(f.manufacturer_part_primary.resolution,'unresolved');assert.equal(f.customer_uom.resolution,'reviewer_accepted');});
test('empty shared-formula expressions are preserved as unverified metadata',()=>{const book=readWorkbook(readFileSync('../attachments/8e933fef-5f19-4144-b944-9b1961b4ee51/Safety PPE Supplies 2024 FL.xlsx'));assert.ok(book.sheets.some(s=>Object.values(s.cells).some(c=>c.formula==='[unresolved shared formula]')));});
test('all five original source workbooks map to valid canonical drafts independently checked by Python',()=>{const paths=['attachments/8e933fef-5f19-4144-b944-9b1961b4ee51/Safety PPE Supplies 2024 FL.xlsx','attachments/a8b4fa56-bbb4-4d76-8e6a-50a859f829fc/RFQ for PPE.xlsx','attachments/e6f63120-98ee-4723-92b3-e6959045d7c5/TESLA PPE RFP April 2025.xlsx','attachments/fac704a8-4ebc-4e40-9bab-2a32a330cd7a/grainger-030926.xlsx','attachments/5c3b8658-ae6e-4236-aa3e-731f507b82fc/PPE List.xlsx'];for(const path of paths){const bytes=readFileSync('../'+path),book=readWorkbook(bytes),records=extract(book).records,columns=Object.fromEntries([...new Set(records.flatMap(r=>Object.keys(r.extras)))].map(k=>[k,'pending'])),snap=buildCanonical({book,records,columns,name:path.split('/').at(-1),digest:createHash('sha256').update(bytes).digest('hex'),templateDigest,controller:createReviewController()});assert.deepEqual(validate(snap.run,{trusted:snap.trusted}),[],path);const py=spawnSync(process.env.PYTHON || 'python3',['-c',"import sys,json;sys.path.insert(0,'lib/canonical/reference');from validator import validate;print(json.dumps(validate(json.load(sys.stdin))))"],{input:JSON.stringify(snap.run),encoding:'utf8',maxBuffer:10*1024*1024});assert.equal(py.status,0,py.stderr);assert.deepEqual(JSON.parse(py.stdout),[],path);assert.equal(snap.run.items.length,records.length);assert.equal(snap.run.evidence.length,book.population);}});
