import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from './helpers/fixtures.mjs';
import {coverageIndex,coverageStats,prepareCoverage,applyCoverage,approveLayout,checkCoverage,currentCoverage} from '../lib/canonical/coverage.mjs';
import {createReviewController,buildCanonical,checkCanonical} from '../lib/canonical/bridge.mjs';
import {captureDecision,assertCurrentDecision} from '../lib/canonical/decisions.mjs';
import {makeRecord,readWorkbook,extract,exportWorkbook} from '../lib/workbook.mjs';
const cell=raw=>({raw,type:'inlineStr',formula:null});
function setup(){const book={sheets:[{name:'Items',hidden:'visible',hiddenRows:['2'],cells:{A1:cell('Product'),A2:cell('Glove'),B2:cell('000123'),C2:cell('EA')}},{name:'Notes',hidden:'hidden',hiddenRows:[],cells:{A1:cell('Supplier alternative quote'),A2:{raw:'3',type:'n',formula:'SUM(A1)'}}}]},r=makeRecord(book.sheets[0],['A2']),controller=createReviewController();r.values.E={value:'Glove',evidence:['A2'],reason:'Original description',status:'pending'};r.values.H={value:'Maker',evidence:[],reason:'Human assertion',status:'pending'};r.values.I={value:'000123',evidence:['B2'],reason:'Reviewer confirms manufacturer namespace',status:'pending'};r.values.L={value:'EA',evidence:['C2'],reason:'Source unit',status:'pending'};const before=structuredClone(r);r.boundary='include';for(const f of Object.values(r.values))f.status=f.value?'accepted':'blank';controller.record(before,r,'Explicit reviewer decision');return{book,records:[r],controller};}
const index=s=>coverageIndex(s.book,s.records,s.controller);
const classify=(s,sheet,addresses,disposition,role='customer_specification')=>applyCoverage(s.controller,index(s),prepareCoverage(index(s),{sheet,addresses,disposition,role,reason:'Reviewer checked this exact source selection.'}));
function complete(s){classify(s,'Items',['A1'],'header');classify(s,'Items',['A2','B2','C2'],'item');classify(s,'Notes',['A1','A2'],'excluded','quoted_alternate');for(const sh of s.book.sheets)approveLayout(s.controller,index(s),sh.name,'Confirmed original item layout and excluded supplier alternatives.');}
const canonical=s=>buildCanonical({book:s.book,records:s.records,columns:{},name:'bid.xlsx',digest:'a'.repeat(64),templateDigest:'b'.repeat(64),controller:s.controller});
test('coverage counts every original cell, hidden sheets/rows and formulas; nothing is implicitly approved',()=>{const s=setup(),stats=coverageStats(s.controller,index(s));assert.equal(stats.total,6);assert.equal(stats.reviewed,0);assert.equal(stats.unresolved,6);assert.equal(stats.sheets[0].hiddenRows,1);assert.equal(stats.sheets[1].hidden,'hidden');assert.ok(checkCanonical(canonical(s),{reviewed:true,coverage:true}).some(e=>e.code==='COVERAGE_REVIEW_REQUIRED'));});
test('exact classified cells, layout approvals and review events can pass canonical final validation',()=>{const s=setup();complete(s);assert.deepEqual(checkCoverage(s.controller,index(s)),[]);const snap=canonical(s);assert.deepEqual(checkCanonical(snap,{reviewed:true,coverage:true,final:true}),[]);assert.equal(snap.run.evidence.find(e=>e.range==='A1'&&e.sheet_id==='sheet-1').semantic_role,'quoted_alternate');assert.equal(snap.run.regions.flatMap(r=>r.coverage).length,6);const out=exportWorkbook(readFileSync('public/template.xlsx'),s.records,{});assert.equal(readWorkbook(out).sheets.find(sh=>sh.name==='AI BID IDENTIFICATION TEMPLATE').cells.I2.raw,'000123');});
test('stale source batches are rejected atomically, and failed classifications create no approvals',()=>{const s=setup(),i=index(s),plan=prepareCoverage(i,{sheet:'Items',addresses:['A1','A2'],disposition:'header',role:'customer_specification',reason:'Reviewed both cells.'});s.book.sheets[0].cells.A2.raw='Changed source';assert.throws(()=>applyCoverage(s.controller,index(s),plan),/changed/);assert.equal(s.controller.coverage.size,0);assert.throws(()=>prepareCoverage(index(s),{sheet:'Items',addresses:['A1'],disposition:'item',role:'customer_specification',reason:'No item mapping'}),/no included/);assert.throws(()=>prepareCoverage(index(s),{sheet:'Items',addresses:['A1'],disposition:'header',role:'context',reason:' '}));assert.equal(s.controller.revision,13);});
test('item edits invalidate related coverage, preserve unrelated coverage and cannot resurrect prior decisions on reversion',()=>{const s=setup();complete(s);const r=s.records[0],old=structuredClone(r),original=r.values.E.value;r.values.E.value='Changed description';r.values.E.status='pending';s.controller.record(old,r,'Reviewer edit');let stats=coverageStats(s.controller,index(s));assert.equal(stats.stale,3);assert.equal(stats.reviewed,3);assert.equal(currentCoverage(s.controller,index(s),'Notes','A1').disposition,'excluded');const before=structuredClone(r);r.values.E.value=original;r.values.E.status='accepted';s.controller.record(before,r,'Reviewer reversion');stats=coverageStats(s.controller,index(s));assert.equal(stats.stale,3);assert.ok(checkCoverage(s.controller,index(s)).length);});
test('included anchors and exported field evidence cannot be silently excluded',()=>{const s=setup();complete(s);classify(s,'Items',['A2'],'excluded');approveLayout(s.controller,index(s),'Items','Reviewed changed classification');assert.ok(checkCoverage(s.controller,index(s)).some(e=>e.includes('anchors an included item')));assert.ok(checkCoverage(s.controller,index(s)).some(e=>e.includes('still supplies an output value')));});
test('supplier quote evidence cannot contaminate approved product facts',()=>{const s=setup();complete(s);classify(s,'Items',['B2'],'item','quoted_alternate');approveLayout(s.controller,index(s),'Items','B2 is an alternate quote');assert.ok(checkCanonical(canonical(s),{reviewed:true,coverage:true}).some(e=>e.code==='SOURCE_ROLE'));});
test('dependency evidence changes and item context changes reopen values and deliberate blanks',()=>{const s=setup(),r=s.records[0],before=structuredClone(r);r.values.H.evidence=['A1'];r.values.H.status='pending';s.controller.record(before,r,'Changed manufacturer provenance');assert.equal(r.values.I.status,'pending');const old=structuredClone(r);r.values.E.value='New product';r.values.E.status='pending';s.controller.record(old,r,'Changed description');assert.equal(r.values.G.status,'pending');assert.equal(r.values.M.status,'pending');const previous=structuredClone(r);r.section='Different item region';s.controller.record(previous,r,'Changed section');assert.equal(r.boundary,'pending');});
test('AI reconciliation invalidates dependent human approvals without granting new approvals',()=>{const s=setup(),before=structuredClone(s.records),after=structuredClone(s.records);after[0].values.E.value='New AI candidate';after[0].values.E.status='pending';const revisions=s.controller.revision;s.controller.reconcile(before,after);assert.equal(after[0].values.I.status,'pending');assert.equal(after[0].values.G.status,'pending');assert.equal(s.controller.revision,revisions);const snap=buildCanonical({book:s.book,records:after,columns:{},name:'bid.xlsx',digest:'a'.repeat(64),templateDigest:'b'.repeat(64),controller:s.controller});assert.ok(checkCanonical(snap,{reviewed:true}).some(e=>e.code==='REVIEW_UNVERIFIED'));});
test('async and batch tokens reject replaced sources, new review decisions and controller changes',()=>{const state={generation:1,reviewRevision:2,sourceDigest:'a'.repeat(64),controllerRevision:3},token=captureDecision(state);assert.doesNotThrow(()=>assertCurrentDecision(token,{...state}));for(const k of Object.keys(state))assert.throws(()=>assertCurrentDecision(token,{...state,[k]:k==='sourceDigest'?'b'.repeat(64):state[k]+1}),/changed/);assert.ok(Object.isFrozen(token));});
test('excluding then reincluding an item cannot revive its earlier field approvals',()=>{const s=setup(),r=s.records[0],before=structuredClone(r);r.boundary='exclude';s.controller.record(before,r,'Exclude source item');assert.equal(r.values.E.status,'pending');const excluded=structuredClone(r);r.boundary='include';s.controller.record(excluded,r,'Include source item again');assert.equal(r.values.E.status,'pending');assert.ok(checkCanonical(canonical(s),{reviewed:true}).some(e=>e.code==='REVIEW_UNVERIFIED'));});
test('a changed extra-column meaning requires renewed approval even when the name is unchanged',()=>{const s=setup(),meta={meaning:'Raw customer code',benefit:'Preserve identity'};s.controller.column('Source Code','approved',meta);const args={book:s.book,records:s.records,columns:{'Source Code':'approved'},name:'bid.xlsx',digest:'a'.repeat(64),templateDigest:'b'.repeat(64),controller:s.controller};assert.equal(buildCanonical({...args,columnMeta:{'Source Code':meta}}).run.extensions[0].status,'approved');assert.equal(buildCanonical({...args,columnMeta:{'Source Code':{...meta,meaning:'Manufacturer code'}}}).run.extensions[0].status,'proposed');});
test('full coverage includes all original sample sheets and cells outside proposed items',()=>{const bytes=readFileSync('../attachments/e6f63120-98ee-4723-92b3-e6959045d7c5/TESLA PPE RFP April 2025.xlsx'),book=readWorkbook(bytes),records=extract(book).records,controller=createReviewController(),stats=coverageStats(controller,coverageIndex(book,records,controller));assert.equal(stats.total,book.population);assert.equal(stats.sheets.length,book.sheets.length);assert.equal(stats.unresolved,book.population);assert.ok(book.sheets.some(s=>!records.some(r=>r.sheet===s.name)));});
