import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {extract,readWorkbook,checkReady} from '../lib/workbook.mjs';
import {prepareDescriptions} from '../lib/description-policy.mjs';
import {identifierLoss} from '../lib/identifier-retention.mjs';
import {createReviewController,buildCanonical,checkCanonical} from '../lib/canonical/bridge.mjs';
import {coverageIndex,prepareCoverage,applyCoverage,approveLayout} from '../lib/canonical/coverage.mjs';
import {exportReviewedWorkbook} from '../lib/canonical/export.mjs';
import {applyProposal,buildScope} from '../lib/ai/client.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex'),proposal=readFileSync('../attachments/fac704a8-4ebc-4e40-9bab-2a32a330cd7a/grainger-030926.xlsx'),template=readFileSync('public/template.xlsx');
function setup(){const book=readWorkbook(proposal),records=prepareDescriptions(extract(book).records,book);return {book,records,controller:createReviewController(),columns:{'Source Product ID':'declined'},name:'Grainger.xlsx',digest:hash(proposal),templateDigest:hash(template),proposalBytes:proposal,templateBytes:template,expectedSourceDigest:hash(proposal),coverageConfirmed:true};}
test('all 31 Grainger records retain full original narratives and codes beside consistently isolated product wording',()=>{const s=setup();assert.equal(s.records.length,31);for(const r of s.records){assert.ok(!r.values.E.value.includes('Item #'));assert.ok(!r.values.E.value.includes('Order '));assert.equal(r.values.F.value,r.anchors.map(a=>s.book.sheets[0].cells[a].raw.trim()).join(' '));assert.ok(r.values.F.value.includes(r.extras['Source Product ID'].value));}assert.equal(s.records.find(r=>r.anchors[0]==='A38').values.E.value,'HYFLEX Coated Glove; Size XL (10)');assert.ok(s.records.at(-1).values.F.value.includes('recycle program'));assert.deepEqual(identifierLoss(s.records,s.columns),[]);const first=structuredClone(s.records);prepareDescriptions(s.records,s.book);assert.deepEqual(s.records,first);});
test('AI cannot replace the preserved full narrative with a short specification',()=>{const s=setup(),r=s.records[15],input=buildScope(s.book,[r],{digest:s.digest,scopeId:'test-narrative'}),envelope={digest:s.digest,scopeId:'test-narrative',proposal:{items:[{recordId:r.id,sheet:r.sheet,anchors:r.anchors,section:'',ambiguous:false,boundaryReason:'One item',fields:[{column:'F',value:'Tyvek',kind:'source_span',identifierType:'not_identifier',reason:'Material',evidence:[{sheet:r.sheet,cell:r.anchors[0],quote:'Tyvek'}]}],extras:[]}],warnings:[]}};const result=applyProposal([r],s.book,input,envelope);assert.equal(result.records[0].values.F.value,r.values.F.value);});
test('tabular descriptions are untouched and code-loss checks accept only a retained output token',()=>{const s=setup(),r=s.records[0];s.columns['Source Product ID']='pending';r.values.F.value='';assert.equal(identifierLoss([r],s.columns).length,1);r.values.F.value='X22EY58Z';assert.equal(identifierLoss([r],s.columns).length,1);r.values.F.value='Stock code: 22EY58';assert.equal(identifierLoss([r],s.columns).length,0);r.values.F.value='';assert.equal(identifierLoss([r],{'Source Product ID':'approved'}).length,0);r.boundary='exclude';assert.equal(identifierLoss([r],s.columns).length,0);const book=readWorkbook(readFileSync('../attachments/a8b4fa56-bbb4-4d76-8e6a-50a859f829fc/RFQ for PPE.xlsx')),rows=extract(book).records,before=structuredClone(rows);prepareDescriptions(rows,book);assert.deepEqual(rows,before);});
test('the complete Grainger proposal exports all 31 product/full-narrative pairs through final validation and readback',async()=>{const s=setup();s.controller.automate(s.records,s.book);for(const r of s.records){const before=structuredClone(r);r.boundary='include';r.values.E.status='accepted';s.controller.record(before,r,'Test-only reviewer checks product wording and includes this source occurrence.');s.controller.automate([r],s.book);}s.controller.column('Source Product ID','declined');const index=coverageIndex(s.book,s.records,s.controller),sheet=s.book.sheets[0],linked=new Set(s.records.flatMap(r=>r.anchors));for(const disposition of ['item','context']){const addresses=Object.keys(sheet.cells).filter(a=>linked.has(a)===(disposition==='item'));applyCoverage(s.controller,index,prepareCoverage(index,{sheet:sheet.name,addresses,disposition,role:disposition==='item'?'customer_specification':'context',reason:'Test-only reviewer checks original narratives and separately identifies headings and general instructions.'}));}approveLayout(s.controller,index,sheet.name,'Test-only reviewer checked every source cell and all 31 source occurrences.');assert.deepEqual(checkReady(s.records,s.columns,true),[]);assert.deepEqual(checkCanonical(buildCanonical(s),{reviewed:true,coverage:true,final:true}),[]);const output=readWorkbook(await exportReviewedWorkbook(s)).sheets.find(s=>s.name==='AI BID IDENTIFICATION TEMPLATE');for(const [i,r]of s.records.entries()){assert.equal(output.cells['E'+(i+2)].raw,r.values.E.value);assert.equal(output.cells['F'+(i+2)].raw,r.values.F.value);}for(const row of [9,10,11])assert.equal(output.cells['L'+row].raw,'BX');assert.ok(!output.cells.I2);assert.ok(!output.cells.K2);const snap=buildCanonical(s),d=snap.run.items.find(i=>i.lineage.source_ranges[0]==='A40').fields.description_secondary;assert.equal(d.resolution,'auto_accepted');assert.equal(d.candidates[0].rule_version,'join-v1');snap.run.evidence.find(e=>e.range==='A43').raw_value+=' invented';assert.ok(checkCanonical(snap,{final:true}).some(e=>e.code==='JOIN_VALUE_MISMATCH'));});
