import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from './helpers/fixtures.mjs';
import {createHash} from 'node:crypto';
import {DOMParser,XMLSerializer} from '@xmldom/xmldom';
import {readWorkbook,extract} from '../lib/workbook.mjs';
import {prepareDescriptions} from '../lib/description-policy.mjs';
import {buildScope,applyProposal} from '../lib/ai/client.mjs';
import {validateEvaluation,EVALUATION_TASK} from '../lib/ai/evaluation.mjs';
import {callExtractionAndEvaluation} from '../lib/ai/service.mjs';
import {createReviewController,buildCanonical,checkCanonical} from '../lib/canonical/bridge.mjs';
import {automateBoundaries,automateCoverage,applyEvaluationFindings,pruneRedundantExtras} from '../lib/canonical/pipeline.mjs';
import {coverageStats} from '../lib/canonical/coverage.mjs';
import {sourceDecision,evaluationEligible} from '../lib/canonical/source-policy.mjs';
import {exportReviewedWorkbook,finalReadiness} from '../lib/canonical/export.mjs';
import {reviewStats} from '../lib/ui/review.mjs';
globalThis.DOMParser=DOMParser;globalThis.XMLSerializer=XMLSerializer;
const hash=b=>createHash('sha256').update(b).digest('hex');
const proposalBytes=readFileSync('../attachments/fac704a8-4ebc-4e40-9bab-2a32a330cd7a/grainger-030926.xlsx'),templateBytes=readFileSync('public/template.xlsx');
function setup(){const book=readWorkbook(proposalBytes),records=prepareDescriptions(extract(book).records,book),controller=createReviewController();pruneRedundantExtras(records);controller.requireEvaluation();automateBoundaries(controller,records,book);controller.automate(records,book);return{book,records,controller,columns:{},name:'Grainger.xlsx',digest:hash(proposalBytes),templateDigest:hash(templateBytes),expectedSourceDigest:hash(proposalBytes),proposalBytes,templateBytes};}
function scope(s,records=s.records.slice(0,10)){
 const input=buildScope(s.book,records,{digest:s.digest,scopeId:'scope-'+records[0].id});
 const proposal={items:records.map(r=>{const a=r.anchors[0],raw=s.book.sheets.find(x=>x.name===r.sheet).cells[a].raw;return{recordId:r.id,sheet:r.sheet,anchors:r.anchors,section:r.section||'',ambiguous:false,boundaryReason:'Explicit source Item # with continuation cells.',fields:[{column:'E',value:r.values.E.value,evidence:[{sheet:r.sheet,cell:a,quote:raw}],reason:'Product wording supported by original narrative.',kind:'normalization',identifierType:'not_identifier'},...(a==='A6'?[{column:'G',value:'2L',evidence:[{sheet:r.sheet,cell:a,quote:'2L'}],reason:'Literal size in this occurrence.',kind:'source_span',identifierType:'not_identifier'}]:[])],extras:[]};}),warnings:[]};
 const evaluation={items:proposal.items.map(p=>({recordId:p.recordId,sheet:p.sheet,anchors:p.anchors,boundary:'supported',reason:'One explicit item occurrence.',fields:p.fields.map(f=>({column:f.column,value:f.value,verdict:'supported',reason:'Exact customer narrative supports the proposed field meaning.',evidence:f.evidence})),missing:[]}))};return{input,proposal,evaluation};
}
function apply(s,batches){const baseline=structuredClone(s.records);let records=s.records;const evaluations=[];for(const {input,proposal,evaluation}of batches){evaluations.push(validateEvaluation({source:input,proposal},evaluation));records=applyProposal(records,s.book,input,{digest:s.digest,scopeId:input.scopeId,proposal}).records;}applyEvaluationFindings(records,evaluations,s.controller);pruneRedundantExtras(records);s.controller.reconcile(baseline,records);automateBoundaries(s.controller,records,s.book);s.controller.automate(records,s.book);s.controller.evaluate(records,s.book,evaluations);s.records=records;s.coverageConfirmed=automateCoverage(s.controller,s.book,records).complete;return s;}
test('real 31-item Grainger workbook exports without simulated human row/field/layout approvals when grounded evaluation supports candidates',async()=>{
 const s=setup(),batches=[];for(let i=0;i<s.records.length;i+=10)batches.push(scope(s,s.records.slice(i,i+10)));
 assert.ok(finalReadiness(s).messages.some(x=>x.includes('separate source evaluation')));
 apply(s,batches);const stats=reviewStats(s.records,s.columns);assert.equal(stats.pendingItems,0);assert.equal(stats.total,31);assert.equal(s.controller.fields.size,0);assert.ok([...s.controller.boundaries.values()].every(x=>x.system));assert.equal(s.records.find(r=>r.anchors[0]==='A6').values.G.status,'auto_evaluated');
 const snapshot=buildCanonical(s);assert.deepEqual(checkCanonical(snapshot,{reviewed:true,coverage:true,final:true}),[]);assert.equal(snapshot.run.review_events.length,0);assert.deepEqual(finalReadiness(s).messages,[]);
 const coverage=automateCoverage(s.controller,s.book,s.records);assert.equal(coverageStats(s.controller,coverage.index).unresolved,0);const revision=s.controller.revision;automateBoundaries(s.controller,s.records,s.book);s.controller.automate(s.records,s.book);automateCoverage(s.controller,s.book,s.records);assert.equal(s.controller.revision,revision,'automatic passes are idempotent');
 const output=readWorkbook(await exportReviewedWorkbook(s)).sheets.find(x=>x.name==='AI BID IDENTIFICATION TEMPLATE');assert.equal(Object.keys(output.cells).filter(a=>/^E\d+$/.test(a)&&a!=='E1').length,31);assert.equal(output.cells.G6.raw,'2L');assert.ok(output.cells.F6.raw.includes('53YK95'));assert.equal(output.cells.N2,undefined);
});
test('evaluator disagreements and important missing facts become exceptions and cannot be reaccepted by source automation',()=>{
 const s=setup(),batch=scope(s),review=batch.evaluation.items[0];review.fields[0].verdict='review';review.fields[0].reason='Product wording is ambiguous.';const missing=batch.evaluation.items[1];missing.missing=[{column:'H',reason:'Manufacturer was not placed in its field.',evidence:[{sheet:missing.sheet,cell:missing.anchors[0],quote:'MSA'}]}];apply(s,[batch]);assert.equal(s.records[0].values.E.status,'pending');assert.match(s.records[0].values.E.reason,/Evaluator requires review/);assert.equal(s.records[1].values.H.status,'pending');s.controller.automate(s.records,s.book);assert.equal(s.records[0].values.E.status,'pending');assert.equal(s.records[1].values.H.status,'pending');assert.equal(reviewStats(s.records,{}).pendingItems,2);
});
test('evaluator boundary concern cannot be silently overridden by the deterministic item rule',()=>{const s=setup(),batch=scope(s);batch.evaluation.items[0].boundary='review';batch.evaluation.items[0].reason='Possible second requested occurrence in continuation.';apply(s,[batch]);automateBoundaries(s.controller,s.records,s.book);assert.equal(s.records[0].boundary,'pending');assert.ok(!s.coverageConfirmed);});
test('changed values, omitted fields, fabricated quotes, approval flags and unrelated evidence fail evaluation validation',()=>{
 const s=setup(),b=scope(s);for(const mutate of [e=>e.items[0].fields[0].value='invented',e=>e.items[0].fields=[],e=>e.items[0].fields[0].evidence[0].quote='fabricated',e=>e.items[0].approved=true,e=>e.items=[],e=>e.items[0].fields[0].evidence=[{sheet:'Sheet1',cell:'A1',quote:s.book.sheets[0].cells.A1.raw}]]){const e=structuredClone(b.evaluation);mutate(e);assert.throws(()=>validateEvaluation({source:b.input,proposal:b.proposal},e));}
});
test('extraction and evaluation use two separate provider calls; evaluator failure returns no success envelope',async()=>{
 const s=setup(),b=scope(s,s.records.slice(0,1)),sent=[],events=[];const mock=async(url,options)=>{const body=JSON.parse(options.body);sent.push(body);return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(sent.length===1?b.proposal:b.evaluation)}]}]});};
 const out=await callExtractionAndEvaluation(b.input,{key:'test-secret',fetchImpl:mock,observer:e=>events.push(e)});assert.equal(sent.length,2);assert.equal(sent[1].instructions,EVALUATION_TASK);assert.notEqual(sent[0].instructions,sent[1].instructions);assert.deepEqual(JSON.parse(sent[1].input[0].content).proposal,b.proposal);assert.ok(sent.every(x=>x.store===false&&!x.tools));assert.ok(events.some(x=>x.stage==='evaluate'&&x.status==='validated'));assert.ok(!JSON.stringify(out).includes('test-secret'));
 let calls=0;await assert.rejects(callExtractionAndEvaluation(b.input,{key:'test-secret',fetchImpl:async()=>Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(++calls===1?b.proposal:{items:[]})}]}]})}));assert.equal(calls,2);
});
test('formula, hidden, supplier, conflicting and pack facts cannot acquire evaluated approval from a supported verdict',()=>{const s=setup(),r=s.records[0],a=r.anchors[0],field={value:'MSA',status:'pending',evidence:[a],reason:'Explicit source name.',origin:'ai'};assert.ok(evaluationEligible(r,'H',field,s.book));assert.equal(evaluationEligible(r,'M',field,s.book),false);for(const reason of ['Conflicting source values','review this decision again','routing instructions'])assert.equal(evaluationEligible(r,'H',{...field,reason},s.book),false);s.book.sheets[0].cells[a].formula='A1';assert.equal(evaluationEligible(r,'H',field,s.book),false);s.book.sheets[0].cells[a].formula=null;s.book.sheets[0].hiddenRows=['2'];assert.equal(evaluationEligible(r,'H',field,s.book),false);
 const tesla={sheets:[{name:'Bundled Bid-Recurring',hidden:'visible',hiddenRows:[],cells:{B4:{raw:'Item Description'},E4:{raw:'Manufacturer Part Number'},J5:{raw:'MSA'}}}]};assert.equal(evaluationEligible({...r,sheet:tesla.sheets[0].name},'H',{...field,evidence:['J5']},tesla),false);
});
test('missed extra item text, formulas and unrecognized source regions remain coverage exceptions',()=>{const s=setup();s.book.sheets[0].cells.A44={raw:'Item # EXTRA (another requested product)',formula:null,type:'inlineStr'};s.book.sheets[0].cells.A45={raw:'Undocumented instruction',formula:null,type:'inlineStr'};s.book.sheets[0].cells.A46={raw:'10',formula:'SUM(A1)',type:'n'};const result=automateCoverage(s.controller,s.book,s.records);assert.equal(result.complete,false);assert.equal(coverageStats(s.controller,result.index).unresolved,3);assert.equal(sourceDecision(result.index,'Sheet1','A44'),null);
});
test('editing upstream wording invalidates evaluated size and altered original bytes block export',async()=>{const s=setup();apply(s,[scope(s)]);const r=s.records.find(r=>r.anchors[0]==='A6'),before=structuredClone(r);r.values.E.value+=' changed';r.values.E.status='edited';s.controller.record(before,r,'Reviewer changed product wording.');s.controller.automate([r],s.book);assert.equal(r.values.G.status,'pending');assert.ok(finalReadiness(s).messages.length);await assert.rejects(exportReviewedWorkbook({...s,expectedSourceDigest:'b'.repeat(64)}),/Source changed/);});

test('later AI batches retain recognized table headers proving annual quantity and identifier meaning',()=>{const book=readWorkbook(readFileSync('../attachments/a8b4fa56-bbb4-4d76-8e6a-50a859f829fc/RFQ for PPE.xlsx')),records=extract(book).records.slice(20,30),input=buildScope(book,records,{digest:hash(proposalBytes),scopeId:'later-hyundai'});assert.ok(input.cells.some(c=>c.cell==='E17'&&/annual/i.test(c.raw)));assert.ok(input.cells.some(c=>c.cell==='D17'&&/product|model/i.test(c.raw)));});
