import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from './helpers/fixtures.mjs';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {readWorkbook,extract} from '../lib/workbook.mjs';
import {verifyConstantFormula,formulaReview,packagingReview,confirmPackaging} from '../lib/canonical/quantity-review.mjs';
import {createReviewController,buildCanonical} from '../lib/canonical/bridge.mjs';
import {automateBoundaries,automateCoverage} from '../lib/canonical/pipeline.mjs';
import {exportReviewedWorkbook,finalReadiness} from '../lib/canonical/export.mjs';
import {validate} from '../lib/canonical/validator.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');
function setup(){const proposalBytes=readFileSync('../attachments/a8b4fa56-bbb4-4d76-8e6a-50a859f829fc/RFQ for PPE.xlsx'),templateBytes=readFileSync('public/template.xlsx'),book=readWorkbook(proposalBytes),records=extract(book).records,controller=createReviewController(),columns=Object.fromEntries([...new Set(records.flatMap(r=>Object.keys(r.extras)))].map(k=>[k,'approved']));automateBoundaries(controller,records,book);controller.automate(records,book);for(const k of Object.keys(columns))controller.column(k,'approved');return{book,records,controller,columns,proposalBytes,templateBytes,name:'RFQ for PPE.xlsx',digest:hash(proposalBytes),expectedSourceDigest:hash(proposalBytes),templateDigest:hash(templateBytes),coverageConfirmed:true};}
function acceptFormula(s,r){const before=structuredClone(r);r.values.K.status='accepted';r.values.K.reason='Test-only simulated reviewer confirms the annual period and purchasing unit after checking arithmetic.';s.controller.record(before,r,'Simulated quantity review');s.controller.approveFormula(r,s.book,'Simulated reviewer confirms arithmetic, annual period and unit.');}
function reviewAll(s){for(const r of s.records){if(packagingReview(r,s.book)){const after=confirmPackaging(r,s.book,true);s.controller.record(r,after,'Test-only simulated reviewer confirms annual quantities count the source containers; this is not an analyst assertion about the actual bid.');Object.assign(r,after);if(formulaReview(r,s.book))s.controller.approveFormula(r,s.book,'Simulated reviewer confirms formula and annual container count.');}else if(formulaReview(r,s.book))acceptFormula(s,r);}s.controller.automate(s.records,s.book);automateCoverage(s.controller,s.book,s.records,s.columns);}
test('bounded arithmetic reproduces both source RFQ quantities exactly without executing workbook text',()=>{const s=setup();assert.equal(formulaReview(s.records.find(r=>r.anchors[0]==='C28'),s.book).result,'9600');assert.equal(formulaReview(s.records.find(r=>r.anchors[0]==='C32'),s.book).result,'19200');for(const [formula,cached]of [['=(2+3)*4','20'],['0.1+0.2','0.3'],['1/8','0.125'],['-2+3','1'],['1-1','0']])assert.equal(verifyConstantFormula(formula,cached).ok,true,formula);for(const [formula,cached]of [['800*1*12','9601'],['A1*12','12'],['SUM(1,2)','3'],['[other.xlsx]A1','4'],['process.exit()','0'],['1/0','0'],['1/3','0.333333333333333'],['2-3','-1'],['1 2','12'],['2**3','8'],['(1+2','3'],['999999999999999*2','1999999999999998'],['1+'.repeat(100)+'1','101']])assert.equal(verifyConstantFormula(formula,cached).ok,false,formula);});
test('nine original pack expressions keep their container and explicit pair content, never inferring pieces',()=>{const s=setup(),packs=s.records.map(r=>packagingReview(r,s.book)).filter(Boolean);assert.equal(packs.length,9);const pairs=packs.find(p=>p.raw==='200 PR/BX');assert.equal(pairs.count,200);assert.equal(pairs.container,'BX');assert.equal(pairs.content,'PR');assert.ok(packs.some(p=>p.raw==='100/BX'&&p.content===null));});
test('packaging review offers deliberate annual blank and rejects unsupported or changed relationships',()=>{const s=setup(),r=s.records.find(r=>r.anchors[0]==='C32'),after=confirmPackaging(r,s.book,false);s.controller.record(r,after,'Simulated reviewer cannot confirm the annual unit.');assert.equal(after.values.K.value,'');assert.equal(after.values.K.status,'blank');assert.equal(after.values.M.status,'accepted');assert.ok(after.values.M.packReview);assert.equal(s.controller.formulaVerified(after,s.book,'E32'),false);for(const mutate of [b=>b.sheets[0].cells.E26.raw='Monthly volume',b=>b.sheets[0].hiddenRows.push('26'),b=>b.sheets[0].cells.D26.raw='Unlabeled',b=>b.sheets[0].cells.E32.raw='19201']){const b=structuredClone(s.book);mutate(b);assert.throws(()=>confirmPackaging(r,b,true),/Annual quantity/);}for(const mutate of [x=>x.values.M.evidence=['G19'],x=>x.values.M.evidence.push('G19'),x=>x.values.M.alternatives=[{value:'2'}],x=>x.values.L.value='EA',x=>x.values.M.value='201']){const x=structuredClone(r);mutate(x);assert.equal(packagingReview(x,s.book),null);}});
test('formula approval requires a real current field decision and expires when source or purchasing context changes',()=>{const s=setup(),r=s.records.find(r=>r.anchors[0]==='C28');r.values.K.status='accepted';assert.throws(()=>s.controller.approveFormula(r,s.book,'forged status'),/verified/);r.values.K.status='pending';acceptFormula(s,r);assert.equal(s.controller.formulaVerified(r,s.book,'E28'),true);for(const mutate of [x=>x.values.L.value='BX',x=>x.values.E.value='Different item',x=>x.values.K.value='9601',x=>x.values.K.status='pending',x=>x.boundary='exclude']){const x=structuredClone(r);mutate(x);assert.equal(s.controller.formulaVerified(x,s.book,'E28'),false);}for(const mutate of [b=>b.sheets[0].cells.E28.formula='800*12+1',b=>b.sheets[0].cells.E28.raw='9601',b=>b.sheets[0].cells.E26.raw='Monthly',b=>b.sheets[0].cells.E26.raw='Annual total revised',b=>b.sheets[0].cells.G28.raw='BX',b=>b.sheets[0].hiddenRows.push('26')]){const b=structuredClone(s.book);mutate(b);assert.equal(s.controller.formulaVerified(r,b,'E28'),false);}const after=structuredClone(r);after.values.L.value='BX';after.values.L.status='edited';s.controller.record(r,after,'Change purchasing unit');assert.equal(after.values.K.status,'pending');});
test('full RFQ passes final export and readback only after focused relationship and formula decisions',async()=>{const s=setup();assert.ok(finalReadiness(s).messages.length);reviewAll(s);assert.deepEqual(finalReadiness(s).messages,[]);const snap=buildCanonical(s),out=readWorkbook(await exportReviewedWorkbook(s)).sheets.find(x=>x.name==='AI BID IDENTIFICATION TEMPLATE');assert.equal(snap.run.items.length,35);for(const [i,r]of s.records.entries()){for(const col of ['K','L','M'])assert.equal(out.cells[col+(i+2)]?.raw||'',r.values[col].value);assert.equal(out.cells[String.fromCharCode(78+Object.keys(s.columns).indexOf('Source Product ID'))+(i+2)]?.raw||'',r.extras['Source Product ID']?.value||'');}assert.equal(snap.run.evidence.filter(e=>e.formula_verified).length,2);const pair=snap.run.items.find(i=>i.lineage.source_ranges[0]==='C52').fields.pack_quantity;assert.equal(pair.candidates[0].value.count,200);assert.equal(pair.candidates[0].value.content_uom.code,'PR');assert.equal(pair.candidates[0].value.count_basis,'pair');});
test('JavaScript and Python validators reject forged or stale formula verification',()=>{const s=setup();reviewAll(s);const snap=buildCanonical(s),trusted=Object.fromEntries(Object.entries(snap.trusted).map(([k,v])=>[k,[...v]]));const py=`import sys,json\nsys.path.insert(0,'lib/canonical/reference')\nfrom validator import validate\nd=json.load(sys.stdin);t={}\nfor k,v in d['trusted'].items():\n if k in ('layout_approvals','review_event_ids'):t[k]=set(v)\n else:t[k]={tuple(json.loads(a)) if a.startswith('[') else a:b for a,b in v}\nprint(json.dumps(validate(d['run'],final=True,trusted=t)))\n`;for(const changed of [false,true]){const run=structuredClone(snap.run);if(changed)run.evidence.find(e=>e.formula_verified).formula='1+1';const result=spawnSync(process.env.PYTHON || 'python3',['-c',py],{input:JSON.stringify({run,trusted}),encoding:'utf8'});assert.equal(result.status,0,result.stderr);const codes=es=>[...new Set(es.map(e=>e.code))].sort();const js=validate(run,{final:true,trusted:snap.trusted});assert.deepEqual(codes(js),codes(JSON.parse(result.stdout)));if(changed)assert.ok(js.some(e=>e.code==='FORMULA_APPROVAL_UNVERIFIED'));else assert.deepEqual(js,[]);}const fake=structuredClone(snap.run);fake.evidence.find(e=>!e.formula_verified).formula_verified=true;assert.ok(validate(fake,{final:true,trusted:snap.trusted}).some(e=>e.code==='FORMULA_APPROVAL_UNVERIFIED'));});
