import {test} from 'node:test';
import assert from 'node:assert/strict';
import {partitionProposal,validateProposal} from '../lib/ai/contracts.mjs';
import {partitionEvaluation} from '../lib/ai/evaluation.mjs';
import {processStages,requestStage} from '../lib/ai/stages.mjs';
import {applyExtractionIssues,buildScope} from '../lib/ai/client.mjs';
import {callExtractionStage,callEvaluationStage} from '../lib/ai/service.mjs';
import {reviewStats} from '../lib/ui/review.mjs';
import {readWorkbook,extract} from '../lib/workbook.mjs';
import {createReviewController} from '../lib/canonical/bridge.mjs';
import {readFileSync} from 'node:fs';
const scope={mode:'enrich',digest:'a'.repeat(64),scopeId:'test',cells:[{sheet:'Items',cell:'B8',raw:'Glove 2L; 100/BX',formula:null,eligibleAnchor:true,contextRole:'item'},{sheet:'Items',cell:'G4',raw:'# of Pieces in a UoM',formula:null,eligibleAnchor:false,contextRole:'header'},{sheet:'Items',cell:'G8',raw:'10',formula:null,eligibleAnchor:true,contextRole:'item'}],records:[{id:'one',sheet:'Items',anchors:['B8'],currentValues:{E:'Glove'}}]};
const field=(column,value,entries)=>({column,value,kind:'source_span',identifierType:'not_identifier',reason:'Literal source.',evidence:entries.map(([cell,quote])=>({sheet:'Items',cell,quote}))});
const proposal=()=>({items:[{recordId:'one',sheet:'Items',anchors:['B8'],section:'',boundaryReason:'One row',ambiguous:false,fields:[field('G','2L',[['B8','2L']]),field('M','10',[['G8','10'],['G4','# of Pieces in a UoM']])],extras:[]}],warnings:[]});
const evaluation=p=>({items:p.items.map(i=>({recordId:i.recordId,sheet:i.sheet,anchors:i.anchors,boundary:'supported',reason:'Source supported.',fields:i.fields.map(f=>({...Object.fromEntries(['column','value','reason','evidence'].map(k=>[k,structuredClone(f[k])])),verdict:'supported'})),missing:[]}))});
test('verified pieces/UOM heading is usable; other product rows cannot pose as headings',()=>{assert.equal(validateProposal(scope,proposal()).items[0].fields.length,2);const wrong=structuredClone(scope);wrong.cells[1].contextRole='item';assert.throws(()=>validateProposal(wrong,proposal()),/crosses/);});
test('bad field is quarantined while literal 2L and source occurrence survive; scope changes remain fatal',()=>{const p=proposal();p.items[0].fields[1].evidence[0].quote='invented';const clean=partitionProposal(scope,p);assert.equal(clean.proposal.items[0].fields[0].value,'2L');assert.equal(clean.issues[0].column,'M');p.items[0].anchors=['B9'];assert.throws(()=>partitionProposal(scope,p));});
test('missing evaluator field or fabricated quote becomes an explicit review verdict',()=>{const p=proposal(),e=evaluation(p);e.items[0].fields[0].evidence[0].quote='made up';e.items[0].fields.pop();const clean=partitionEvaluation({source:scope,proposal:p},e);assert.deepEqual(clean.items[0].fields.map(f=>f.verdict),['review','review']);});
test('evaluator changed scope or unverified missing-information findings remain fatal',()=>{const p=proposal(),e=evaluation(p);e.items[0].recordId='different';assert.throws(()=>partitionEvaluation({source:scope,proposal:p},e));});
test('quarantined absent fields remain pending after automatic rules; human blanks remain deliberate',()=>{const book={sheets:[{name:'Items',hidden:'visible',hiddenRows:[],cells:Object.fromEntries(scope.cells.map(c=>[c.cell,c]))}]},r={id:'one',sheet:'Items',anchors:['B8'],values:{M:{value:'',evidence:[],status:'auto_blank',reason:''}},extras:{}};applyExtractionIssues([r],[{recordId:'one',sheet:'Items',anchors:['B8'],column:'M',reason:'Unverified fact.'}]);createReviewController().automate([r],book);assert.equal(r.values.M.status,'pending');r.values.M.status='blank';applyExtractionIssues([r],[{recordId:'one',sheet:'Items',anchors:['B8'],column:'M',reason:'Unverified fact.'}]);assert.equal(r.values.M.status,'blank');});
test('retry resumes extraction cache after evaluation failure and rejects a changed source',async()=>{const cache=new Map(),calls=[];let fail=true;const send=async(stage,input)=>{calls.push(stage);if(stage==='evaluate'&&fail){fail=false;throw Error('temporary failure');}return{digest:scope.digest,scopeId:scope.scopeId,...(stage==='extract'?{proposal:proposal()}:{evaluation:evaluation(proposal())})};};await assert.rejects(processStages(scope,{cache,check:()=>{},send}));await processStages(scope,{cache,check:()=>{},send});assert.deepEqual(calls,['extract','evaluate','evaluate']);await assert.rejects(processStages({...scope,digest:'b'.repeat(64)},{cache,check:()=>{},send}),/Cached/);});
test('a decision changed during a request discards that stage before caching',async()=>{let current=true;const cache=new Map();await assert.rejects(processStages(scope,{cache,check:()=>{if(!current)throw Error('changed');},send:async()=>{current=false;return{digest:scope.digest,scopeId:scope.scopeId,proposal:proposal()};}}),/changed/);assert.equal(cache.get(scope.scopeId).extract,undefined);});
test('HTML failures are reported as incomplete service results rather than JSON syntax errors',async()=>{await assert.rejects(requestStage('extract',scope,{fetchImpl:async()=>new Response('<!DOCTYPE html>',{status:504})}),e=>e.status===504&&!e.message.includes('Unexpected token'));});
test('new provider stages each make only one bounded provider call',async()=>{let calls=0;const mock=output=>async(url,init)=>{calls++;assert.equal(JSON.parse(init.body).max_output_tokens,7000);return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(output)}]}]});};const extracted=await callExtractionStage(scope,{key:'test',fetchImpl:mock(proposal())});await callEvaluationStage({source:scope,proposal:extracted.proposal},{key:'test',fetchImpl:mock(evaluation(proposal()))});assert.equal(calls,2);});
test('manually reviewed item is complete but not counted as entirely automatic',()=>{const r={boundary:'include',values:{E:{value:'Glove',status:'auto_accepted'},G:{status:'accepted'},M:{status:'auto_blank'}},extras:{}};assert.equal(reviewStats([r]).automaticItems,0);r.values.G.status='auto_evaluated';assert.equal(reviewStats([r]).automaticItems,1);});
test('real Tesla G4 pieces header is labeled as source header in a later item scope',()=>{const book=readWorkbook(new Uint8Array(readFileSync('../attachments/e6f63120-98ee-4723-92b3-e6959045d7c5/TESLA PPE RFP April 2025.xlsx'))),r=extract(book).records.find(r=>r.anchors.includes('B8'));const input=buildScope(book,[r],{digest:scope.digest,scopeId:'tesla'});assert.equal(input.cells.find(c=>c.cell==='G4').contextRole,'header');});

test('pipeline proof bookkeeping stays current, while source/reviewer/owner changes reject results',async()=>{const {capturePipeline,assertCurrentPipeline}=await import('../lib/canonical/decisions.mjs');const current={generation:1,reviewRevision:2,sourceDigest:'a',runId:'run',controllerRevision:10},token=capturePipeline(current);assert.doesNotThrow(()=>assertCurrentPipeline(token,{...current,controllerRevision:100}));for(const field of ['generation','reviewRevision','sourceDigest','runId'])assert.throws(()=>assertCurrentPipeline(token,{...current,[field]:'changed'}));});

test('small Grainger scopes exclude unrelated original item narratives',()=>{const book=readWorkbook(new Uint8Array(readFileSync('../attachments/fac704a8-4ebc-4e40-9bab-2a32a330cd7a/grainger-030926.xlsx'))),r=extract(book).records[10],input=buildScope(book,[r],{digest:scope.digest,scopeId:'single'});for(const c of input.cells)if(/Item\s*#/i.test(c.raw))assert.ok(r.anchors.includes(c.cell));});
test('Gemini 3 stages explicitly request supported low thinking without exposing thought summaries',async()=>{await callExtractionStage(scope,{provider:'gemini',key:'test',fetchImpl:async(url,init)=>{const body=JSON.parse(init.body);assert.deepEqual(body.generationConfig.thinkingConfig,{thinkingLevel:'low'});return Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(proposal())}]}}]});}});});

test('ordering column naming variants already preserved in the full narrative require no column decision',async()=>{const {pruneRedundantExtras}=await import('../lib/canonical/pipeline.mjs');for(const name of ['Order Note','Order Instructions','Ordering Instructions']){const r={values:{F:{origin:'source_narrative',value:'Glove. Order 20 as needed.'}},extras:{[name]:{value:'Order 20 as needed'}}};pruneRedundantExtras([r]);assert.equal(Object.keys(r.extras).length,0);}});

test('a rejected AI rewrite preserves a independently verified original literal description',()=>{const book={sheets:[{name:'Items',hidden:'visible',hiddenRows:[],cells:{B8:{raw:'Glove 2L; 100/BX',formula:null}}}]},r={id:'one',sheet:'Items',anchors:['B8'],values:{E:{value:'Glove 2L; 100/BX',evidence:['B8'],status:'auto_accepted',direct:true,reason:'Literal original source.',origin:'source'}},extras:{}};applyExtractionIssues([r],[{recordId:'one',sheet:'Items',anchors:['B8'],column:'E',reason:'Unverified rewrite.'}],book);assert.equal(r.values.E.status,'auto_accepted');assert.equal(r.values.E.value,book.sheets[0].cells.B8.raw);r.values.E.value='invented';applyExtractionIssues([r],[{recordId:'one',sheet:'Items',anchors:['B8'],column:'E',reason:'Unverified rewrite.'}],book);assert.equal(r.values.E.status,'pending');});
