import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {readWorkbook,extract} from '../lib/workbook.mjs';
import {prepareDescriptions,productWording} from '../lib/description-policy.mjs';
import {normalizeUnit,purchasingUnit} from '../lib/unit-policy.mjs';
import {automaticRule} from '../lib/canonical/automatic.mjs';
import {applyProposal,buildScope} from '../lib/ai/client.mjs';
function setup(){const book=readWorkbook(readFileSync('../attachments/fac704a8-4ebc-4e40-9bab-2a32a330cd7a/grainger-030926.xlsx'));return {book,records:prepareDescriptions(extract(book).records,book)};}
test('exact plural unit aliases normalize while unfamiliar and composite units remain unresolved',()=>{for(const [raw,code]of Object.entries({boxes:'BX',bags:'BG',pairs:'PR',cases:'CS',packs:'PK',rolls:'RL',dozens:'DZ',' BX ':'BX'}))assert.equal(normalizeUnit(raw),code);for(const raw of ['CA','12 PR/BX','box cutter','packages'])assert.equal(normalizeUnit(raw),null);});
test('ordering instructions supply units without interpreting product words, negation or mixed packaging',()=>{assert.equal(purchasingUnit('Order 5 or 10 boxes per month as needed'),'BX');assert.equal(purchasingUnit('Order a few rolls as needed'),'RL');for(const raw of ['Item # 123 (box cutter)','Order 30-40 every month','Order 2 packages','Order 2 boxes or 3 bags','Order 2 boxes or bags','Do not order 2 boxes'])assert.equal(purchasingUnit(raw),null,raw);});
test('all three actual Grainger box rows have independently reproducible BX decisions',()=>{const {book,records}=setup();for(const anchor of ['A9','A11','A13']){const r=records.find(r=>r.anchors[0]===anchor);assert.equal(r.values.L.value,'BX');assert.equal(automaticRule(r,'L',r.values.L,book)?.rule,'unit-alias-v1');assert.equal(automaticRule(r,'L',{...r.values.L,origin:'ai'},book),null);const changed=structuredClone(book);for(const a of r.anchors)changed.sheets[0].cells[a].raw=changed.sheets[0].cells[a].raw.replace(/boxes/gi,'packages');assert.equal(automaticRule(r,'L',r.values.L,changed),null);const formula=structuredClone(book);formula.sheets[0].cells[anchor].formula='A1';assert.equal(automaticRule(r,'L',r.values.L,formula),null);}});
test('AI shortening and equivalent raw units cannot replace deterministic narrative product or unit defaults',()=>{const {book,records}=setup(),r=records.find(r=>r.anchors[0]==='A9');const input=buildScope(book,[r],{digest:'a'.repeat(64),scopeId:'unit-policy'});const fields=[{column:'E',value:'Glove',quote:'Glove'},{column:'L',value:'boxes',quote:'boxes'}].filter(f=>r.values.F.value.includes(f.quote)).map(f=>({column:f.column,value:f.value,kind:'source_span',identifierType:'not_identifier',reason:'Source wording',evidence:[{sheet:r.sheet,cell:r.anchors.find(a=>book.sheets[0].cells[a].raw.includes(f.quote)),quote:f.quote}]}));const envelope={digest:'a'.repeat(64),scopeId:'unit-policy',proposal:{items:[{recordId:r.id,sheet:r.sheet,anchors:r.anchors,section:'',ambiguous:false,boundaryReason:'One source item',fields,extras:[]}],warnings:[]}};const result=applyProposal([r],book,input,envelope).records[0];assert.equal(result.values.E.value,productWording(r.values.F.value));assert.equal(result.values.L.value,'BX');assert.ok(!result.values.L.alternatives?.length);r.values.E.status='edited';r.values.E.value='Reviewer wording';r.values.L.status='blank';r.values.L.value='';prepareDescriptions([r],book);assert.equal(r.values.E.value,'Reviewer wording');assert.equal(r.values.L.value,'');});
